# Form implementation generated from reading ui file 'dlgExportarDatos.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgExportarDatos(object):
    def setupUi(self, dlgExportarDatos):
        dlgExportarDatos.setObjectName("dlgExportarDatos")
        dlgExportarDatos.resize(894, 201)
        dlgExportarDatos.setMinimumSize(QtCore.QSize(610, 200))
        dlgExportarDatos.setMaximumSize(QtCore.QSize(894, 201))
