# Form implementation generated from reading ui file 'dlgExportarDatos.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgExportarDatos(object):
    def setupUi(self, dlgExportarDatos):
        dlgExportarDatos.setObjectName("dlgExportarDatos")
        dlgExportarDatos.resize(894, 201)
        dlgExportarDatos.setMinimumSize(QtCore.QSize(610, 200))
        dlgExportarDatos.setMaximumSize(QtCore.QSize(894, 201))
        self.gridLayout = QtWidgets.QGridLayout(dlgExportarDatos)
        self.gridLayout.setContentsMargins(150, -1, 150, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.chkClientes = QtWidgets.QCheckBox(dlgExportarDatos)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkClientes.setFont(font)
        self.chkClientes.setObjectName("chkClientes")
        self.gridLayout.addWidget(self.chkClientes, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblDatosExcel = QtWidgets.QLabel(dlgExportarDatos)
        self.lblDatosExcel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.lblDatosExcel.setFont(font)
        self.lblDatosExcel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblDatosExcel.setObjectName("lblDatosExcel")
        self.horizontalLayout.addWidget(self.lblDatosExcel)
        self.label_2 = QtWidgets.QLabel(dlgExportarDatos)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../img/icono_pregunta.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.chkCoches = QtWidgets.QCheckBox(dlgExportarDatos)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkCoches.setFont(font)
        self.chkCoches.setObjectName("chkCoches")
        self.gridLayout.addWidget(self.chkCoches, 5, 0, 1, 1)
        self.btnExportar = QtWidgets.QPushButton(dlgExportarDatos)
        self.btnExportar.setMaximumSize(QtCore.QSize(472, 26))
        self.btnExportar.setObjectName("btnExportar")
        self.gridLayout.addWidget(self.btnExportar, 10, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(dlgExportarDatos)
        self.label_3.setLineWidth(1)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.chkProductos = QtWidgets.QCheckBox(dlgExportarDatos)
        self.chkProductos.setObjectName("chkProductos")
        self.gridLayout.addWidget(self.chkProductos, 4, 0, 1, 1)

        self.retranslateUi(dlgExportarDatos)
        QtCore.QMetaObject.connectSlotsByName(dlgExportarDatos)

    def retranslateUi(self, dlgExportarDatos):
        _translate = QtCore.QCoreApplication.translate
        dlgExportarDatos.setWindowTitle(_translate("dlgExportarDatos", "Exportar Datos"))
        self.chkClientes.setText(_translate("dlgExportarDatos", "Clientes"))
        self.lblDatosExcel.setText(_translate("dlgExportarDatos", "Elija los datos que quiere exportar"))
        self.chkCoches.setText(_translate("dlgExportarDatos", "Coches"))
        self.btnExportar.setText(_translate("dlgExportarDatos", "Exportar"))
        self.label_3.setText(_translate("dlgExportarDatos", "* se exportará a un excel con una hoja diferente para cada dato"))
        self.chkProductos.setText(_translate("dlgExportarDatos", "Productos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgExportarDatos = QtWidgets.QDialog()
    ui = Ui_dlgExportarDatos()
    ui.setupUi(dlgExportarDatos)
    dlgExportarDatos.show()
    sys.exit(app.exec())
