# Form implementation generated from reading ui file 'dlgSeleccionarCliente.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSeleccionCliente(object):
    def setupUi(self, dlgSeleccionCliente):
        dlgSeleccionCliente.setObjectName("dlgSeleccionCliente")
        dlgSeleccionCliente.resize(866, 538)
        self.gridLayout = QtWidgets.QGridLayout(dlgSeleccionCliente)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(dlgSeleccionCliente)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(dlgSeleccionCliente)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(dlgSeleccionCliente)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(dlgSeleccionCliente)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(dlgSeleccionCliente)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabClientes = QtWidgets.QTableWidget(self.groupBox)
        self.tabClientes.setObjectName("tabClientes")
        self.tabClientes.setColumnCount(2)
        self.tabClientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabClientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabClientes.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.tabClientes, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 4)
        self.btnAceptarCliente = QtWidgets.QPushButton(dlgSeleccionCliente)
        self.btnAceptarCliente.setMinimumSize(QtCore.QSize(100, 0))
        self.btnAceptarCliente.setMaximumSize(QtCore.QSize(125, 16777215))
        self.btnAceptarCliente.setObjectName("btnAceptarCliente")
        self.gridLayout.addWidget(self.btnAceptarCliente, 4, 3, 1, 1)

        self.retranslateUi(dlgSeleccionCliente)
        QtCore.QMetaObject.connectSlotsByName(dlgSeleccionCliente)

    def retranslateUi(self, dlgSeleccionCliente):
        _translate = QtCore.QCoreApplication.translate
        dlgSeleccionCliente.setWindowTitle(_translate("dlgSeleccionCliente", "Selecciona cliente"))
        self.label.setText(_translate("dlgSeleccionCliente", "Búsqueda"))
        self.pushButton.setText(_translate("dlgSeleccionCliente", "Buscar"))
        self.pushButton_2.setText(_translate("dlgSeleccionCliente", "Recargar lista"))
        self.groupBox.setTitle(_translate("dlgSeleccionCliente", "Clientes"))
        item = self.tabClientes.horizontalHeaderItem(0)
        item.setText(_translate("dlgSeleccionCliente", "DNI"))
        item = self.tabClientes.horizontalHeaderItem(1)
        item.setText(_translate("dlgSeleccionCliente", "Matrícula"))
        self.btnAceptarCliente.setText(_translate("dlgSeleccionCliente", "Seleccionar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgSeleccionCliente = QtWidgets.QDialog()
    ui = Ui_dlgSeleccionCliente()
    ui.setupUi(dlgSeleccionCliente)
    dlgSeleccionCliente.show()
    sys.exit(app.exec())
