# Form implementation generated from reading ui file 'dlgSeleccionarFactura.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSeleccionCliente(object):
    def setupUi(self, dlgSeleccionCliente):
        dlgSeleccionCliente.setObjectName("dlgSeleccionCliente")
        dlgSeleccionCliente.resize(866, 643)
        self.gridLayout = QtWidgets.QGridLayout(dlgSeleccionCliente)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(dlgSeleccionCliente)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(dlgSeleccionCliente)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabClientes = QtWidgets.QTableWidget(self.groupBox)
        self.tabClientes.setObjectName("tabClientes")
        self.tabClientes.setColumnCount(2)
        self.tabClientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabClientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabClientes.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.tabClientes, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 3)
        self.txtBusqueda = QtWidgets.QLineEdit(dlgSeleccionCliente)
        self.txtBusqueda.setObjectName("txtBusqueda")
        self.gridLayout.addWidget(self.txtBusqueda, 1, 0, 1, 3)
        self.btnCancelar = QtWidgets.QPushButton(dlgSeleccionCliente)
        self.btnCancelar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnCancelar.setObjectName("btnCancelar")
        self.gridLayout.addWidget(self.btnCancelar, 4, 0, 1, 1)
        self.btnAceptar = QtWidgets.QPushButton(dlgSeleccionCliente)
        self.btnAceptar.setMinimumSize(QtCore.QSize(100, 0))
        self.btnAceptar.setMaximumSize(QtCore.QSize(125, 16777215))
        self.btnAceptar.setObjectName("btnAceptar")
        self.gridLayout.addWidget(self.btnAceptar, 4, 1, 1, 1)

        self.retranslateUi(dlgSeleccionCliente)
        QtCore.QMetaObject.connectSlotsByName(dlgSeleccionCliente)

    def retranslateUi(self, dlgSeleccionCliente):
        _translate = QtCore.QCoreApplication.translate
        dlgSeleccionCliente.setWindowTitle(_translate("dlgSeleccionCliente", "Selecciona cliente"))
        self.label.setText(_translate("dlgSeleccionCliente", "Búsqueda"))
        self.groupBox.setTitle(_translate("dlgSeleccionCliente", "Facturas"))
        item = self.tabClientes.horizontalHeaderItem(0)
        item.setText(_translate("dlgSeleccionCliente", "DNI"))
        item = self.tabClientes.horizontalHeaderItem(1)
        item.setText(_translate("dlgSeleccionCliente", "Matrícula"))
        self.btnCancelar.setText(_translate("dlgSeleccionCliente", "Cancelar"))
        self.btnAceptar.setText(_translate("dlgSeleccionCliente", "Seleccionar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgSeleccionCliente = QtWidgets.QDialog()
    ui = Ui_dlgSeleccionCliente()
    ui.setupUi(dlgSeleccionCliente)
    dlgSeleccionCliente.show()
    sys.exit(app.exec())
